### ISSUE TITLE
Quickstart page

### ISSUE THREAD

**Issue by masterdubs** [kusari-network/kusari-docs#1]
Create a quickstart page where we have all the mains infos on one place:
- explorer URL
- chain specs ( net id , ... )
- app url
- forum
- discord 
- ....

**Comment by Neidhardt87** [comment]
[SwapDEX Mainpage](https://swapdex.network)
[Kusari Webpage](https://www.kusari.network/) 
[Kusari Explorer](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fws.kusari.network#/accounts)
MetaMask Information Network : 
Kusari RPC URL : https://rpc.kusari.network/ 
Chain ID : 71 
Currency Symbol : KSI 
[Forum](https://forum.swapdex.network/) 
[Twitter](https://twitter.com/SwapdexO) 
[Telegram](https://t.me/officialswapdexgroup)
[Discord](https://discord.gg/srPcbg9g92)

**Comment by Petar-23** [comment]
Just pushed the new branch containing the quick-start page.

**Comment by Neidhardt87** [comment]
https://app.kusari.network/ is missing as Link to App
