### ISSUE TITLE
FAQs

### ISSUE THREAD

**Issue by Neidhardt87** [kusari-network/kusari-docs#12]
**Disclaimer**
KUSARI is a work in progress. The following FAQs will continue to be updated as the platform evolves. The exact structures and technologies to be included over time and are liable to change with continued research and the possible need for adaptation due to the fast paced development in the crypto industry

### **FAQ**

**What is our mission?**

We’re on a mission to truly decentralise finance
We revolutionize the future of DeFi by providing the industry-leading ecosystem, blockchain, exchange and end-to-end financial platform within a community-governed ecosystem.

**Why do we need KUSARI to help achieve true Decentralisation?**

The distribution of funds in the crypto space is still relatively centralised with the majority of funds in the hands of relatively few.
Part of this is because the technology is still in its youth and adoption still hasn’t reached the masses, although the path towards real mass adoption is getting clearer by the day.
The Problem of centralised funds still persists as a lot of coins and tokens are in the hands of a small number of  big players in the industry.

In order to further disperse these financial resources and give everyone a fair chance of participating in an independent market, exchanges mark a pivotal point. A widespread allocation is only possible if there are a lot of different - ideally independent and decentralised -exchanges that grant access to assets with each acting as a sort of contingency for another, avoiding risk of corruption.

The requirements for those exchanges are steadily rising and rightfully so. Investors want to be able to voice their concerns when putting their hard earned money at risk and the weight of their voice has been rather small in the past. It's clear that it's one of the major challenges for exchanges and DeFi-projects to empower the individual investors and give them the right to vote on important decisions.
With growing desire for participation comes the question on how to meet the needs of the growing crypto community.

KUSARI offers its users participation through an elaborate voting and consensus mechanism that strives to best represent the interest of each and every one of their investors through nominating the most trustworthy validators (nodes that supply the blockchain with the hardware necessary) and voting upon a trusted council to ensure long term stability of the chain and the trading D'Apps deployed on its native KUSARI chain.

### **TECHNICAL FAQ**

**How can i be a part of the chains governance?**

KUSARI encourages active participation from KSI hodlers. Active participation is enabled through Nomination and Validation

If you are looking for a "set-it-and-forget-it" approach to leverage your KSI coins, then becoming a Kusari nominator is the way to go. As a nominator, you are participating in the staking system of Kusari. Nominators use a specified amount of their funds to "vote" for Kusari validators. Validators are network nodes that participate in the consensus and block authoring process. Your job as a nominator is to appoint (stake) your KSI to elect the active set of validators. The active validators list consists of validators that received the most KSI as "votes". If your chosen validator makes it to the active set, he will earn rewards and ideally share them with all of his nominators.

The main difference between a Validator and a Nominator is the active participation in the network. Validators engage in the block production and finality mechanisms, whereas nominators take a more passive role with the above mentioned "set-it-and-forget-it" approach. Being a nominator does not require running a node of your own or worrying about online uptime. However, a good nominator performs due diligence on the validators that they elect. When looking for validators to nominate, a nominator should pay attention to their reward percentage for nominating a specific validator - as well as the risk that they bear of being slashed if the validator gets slashed.

**How many chains can KUSARI connect?**

There is no specific limit to the number of chains that can be connected to the KUSARI network. As long as working bridges exist, there is a way to connect.

**How can i add KUSARI to Metamask?**

Kusari RPC URL : https://rpc.kusari.network/ 
Chain ID : 71 
Currency Symbol : KSI 
Explorer: [https://evm.kusari.network/](https://evm.kusari.network/)

**What is the polkadot.js extenstion? Do i need to get it to interact with the chain?**

[The Polkadot.js](https://polkadot.js.org/extension/) is a browser extension that enables you to create and manage a substrate account (the framework that was used to build i.e. Polkadot, Kusama, the SwapDEX and the KUSARI chain).
In order to interact with the chain and its staking and governance mechanisms, you need to install it.
You can find a video guide [here.](https://www.youtube.com/watch?v=qM36ndMLn5o)

**Where do i find further information on how to become a validator?**

https://docs.kusari.network/validator-guides/validator/

**How can i Nominate/Stake?** 

https://docs.kusari.network/what-to-try/nominator/

**Okay i'm hooked, where are the Deep Dives?**

https://docs.kusari.network/deep-dives/evm-pallet/

**I am a developer, where do i look?**

Work in Progress: https://docs.kusari.network/dev-guides/

**### Community FAQ**

**Where is the the community action?**

Find us on [Discord](https://discord.gg/kC5gwsu25k), [Twitter ](https://twitter.com/swapdexo), [Telegram](https://t.me/officialswapdexgroup) on [reddit](https://www.reddit.com/r/swapdex/) and in our [Forum](https://forum.swapdex.network/)

You can find further information on [Medium](https://medium.com/@swapdex)

**Where can i learn more about the Validators supporting the chain?**

You can check out information provided by the Validators in our [Forum](https://forum.swapdex.network/categories)

**How can i help/support KUSARI**

Take a look at the KUSARI Community Bounty Program -> LINK NEEDED

### **Team FAQ**

**Who is behind KUSARI?**

The Kusari team is an international team of crypto experts and enthusiasts with backgrounds in various professions.
We are mainly based in central Europe (UK, Belgium and Germany) but also work closely together with members in the USA, Australia and Turkey.

**I want to inquire more, how can i contact the officials?**

 Send an Email to marketing@swapdex.network

**### Web3 Foundation**

**What is the Web3 Foundation?**

Web3 Foundation is a Swiss Stiftung established under Article 80 et seqq. of the Swiss Civil Code. The Web3 Foundation was founded by Dr. Gavin Wood and has as its focus the development, deployment and maintenance of “Web3”. Web3 Foundation promotes the development of innovative technologies and applications in the field of cryptographically-enabled decentralised software protocols.

Web3 Foundation’s purpose is to nurture and steward cutting-edge technologies and applications at all levels of the Web3 technology stack. Web3’s principal focus is research, development, deployment, funding, and maintenance of Web3 technologies, plus advocacy and education, developer-adoption, support of middleware, and base-layer/demonstration applications.

The Web3 Foundation Council is Web3’s governing body, responsible for the management of the Web3 Foundation. The current members of the Web3 Foundation Council are Dr. Gavin Wood (President and Founder), Dr. Aeron Buchanan (Vice President) and Reto Trinkler.

Swiss foundations are subject to a mandatory supervision by a federal or cantonal authority. The Web3 Foundation’s application for approval by Eidgenössische Stiftungsaufsicht (Federal Foundation Supervisory Authority) was approved July 2018.

### Risk factors associated with KSI

**Nature of the legal relationship between holders of KSI is uncertain.**

The legal nature of the relationship (if any) between the holders of KSI and the liabilities and obligations of holders of KSI is uncertain.

**Regulatory treatment of KSI is uncertain**

As the sale of tokens is a nascent practice, the treatment of KSI by regulatory and governmental authorities is uncertain and may vary across jurisdictions. The legal and regulatory treatment of KSI may be prone to change in the future, which may have a materially adverse impact on the legal status of KSI, the economic value (if any) of KSI and the liquidity of KSI, as well as the development, function or governance of KUSARI and / or the Web3 Foundation itself.

**Comment by Neidhardt87** [comment]
additional FAQs

**Where can i buy KSI?**

Work in Progress


**Where are the tokenomics?**
-> link to KSI page once done


**Where can i find info about upcoming changes and votes concerning the chain?**

You can check out proposals and referenda via the governance tab on the explorer [here
](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fws.kusari.network#/democracy).
If you want to partake in the discussion about future changes and upcoming proposals, check the [forum](https://forum.swapdex.network) for details.
Upcoming Events concerning the chain can be found on the upcoming [event calendar](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fws.kusari.network#/calendar) as well 

**I am runnning a validator but it says i am on the waiting list. What does that mean?**

Being on the waiting list means that your validator has successfully connected to the chain and is - from a technical standpoint - working as intended. The most likely reason for being in the waiting list is that the amount of KSI nominated (staked) is not high enough to be in the top 300. The amount of nominated (staked) KSI on your validator will determine if you can make it into the top 300. You can go to the targets page of the explorer to check your rank and see how much is needed for you to move into the active set of validators [here ](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fws.kusari.network#/staking/targets) (sort for total stake and check which has the least amount to be eligible for the next era to determine the treshold)

Other reasons may be connectivity issues from you or your providers side. You can check out [discord](https://discord.com/invite/kC5gwsu25k) or the [forum](https://forum.swapdex.network/) and seek help there.


**Can i stop/pause my validator without getting punished?**

Yes, you can set your validator into the "chill" status by going to your "[account actions](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fws.kusari.network#/staking/actions)" page and click on the "STOP" button. This will move your validator into a sleeping stance without losing funds.
Reasons for pausing might be intended migration to another server or an upcoming extended server maintenance.
You might want to inform your Nominators on the KUSARI [Forum](https://forum.swapdex.network/) or on [Discord](https://discord.com/invite/kC5gwsu25k) to give them a heads up about missing payouts.

You can find further information in the [deep dive](https://docs.kusari.network/deep-dives/staking/#chilling).


**I want to switch my VPS provider/Change my server hardware. What do i need to consider?**

NEED CORRECT WAY TO MIGRATE ONE VALIDATOR (what needs to be considered regarding session keys etc)

I ran out of storage on my Validator. How do i migrate without the risk of getting slashed/losing funds?
-> look above


**How do payouts work?**

You can find further explanation regarding block rewards and payouts [here
](https://docs.kusari.network/deep-dives/staking/#staking-rewards-distribution) and [here ](https://docs.kusari.network/validator-guides/validator-payout-overview/#nominators-and-validator-payments)

![reward-distr-02](https://user-images.githubusercontent.com/91843891/148599693-4eaab780-7c4a-4c83-918f-e6ea7fdfc132.png)

**NOTE:** Every party involved with a validator is able to request a payout for their own rewards and additionally has the option to make use of the "payout all" function,  initiating the payout for every party that's eligible for rewards for based upon their respective active eras. Meaning you as a Nominator are not dependent on the Validator to pay out your rewards for you but instead can request your (or everyones payouts) when you need to. Therefore you are not at risk of the Validator missing its 21 day deadline (84 eras) for payouts and are in full control of your funds.



**I am a long term hodler of SDX, how do i claim my KSI?**

You can claim your KSI through our [Dashboard](https://app.kusari.network/#/claim) on a 1 KSI per 100 SDX ratio

Please follow the guide provided in the [video](https://www.youtube.com/watch?v=qM36ndMLn5o)

NOTE: The deadline for calculating KSI wallet holdings is December 3rd, 2021. Any purchases of the ERC-20 SDX-Token after this date will not be considered for the balance claims. 


**How are the rewards calculated?** 

Inflation and Interest rates for KUSARI at the moment
![Kusari Interest and Inflation curve](https://user-images.githubusercontent.com/91843891/148518117-0921ce62-ef49-4966-8468-1b2b38081733.png)

**Comment by Neidhardt87** [comment]
### **Staking FAQs**

**How many active Nominators can a Validator have?**

256 is the amount of Nominations a Validator can recieve. 257 Nominations would mean the Validator is oversubscribed and only the top 256 Nominators (based upon bonded KSI) will be eligible for payouts/rewards.


**What is the maximum number of Validators a Nominator can bond to?**

16 is the maximum number of different validators one Nominator can bond funds to.
NOTE: Due to security reasons, we recommend using a separate Stash and Controller Account for every Nomination

**Comment by Neidhardt87** [comment]
### **Frequently Asked Questions (FAQs)**

This FAQ focuses on technical questions for users interested in developing applications for KUSARI. If you have a more general question, you may wish to search for the answer in our official documentation. If you have a question that is not answered, please feel free to ask for help on our [Discord](https://discord.com/invite/kC5gwsu25k) or our [Telegram.](t.me/officialswapdexgroup)


**KUSARI Launch​**

The Genesis block of the KUSARI network was launched on December-11-2021 11:10:12 UTC, as a nominated Proof of Stake (nPoS) network.


**KUSARI Roadmap​**

For more information on the KUSARI roadmap on its way to decentralise finance,  please visit the LINK to New KSI Homepage Roadmap!


### **Validators​**
 

**What is the minimum bond necessary to create a validator?​**

The minimum stake that is necessary to initially be able to create a validator is as low as 0.1 KSI, which can be changed by the chain's governance. Making it to the list of active validators depends on the amount of KSI that are bonded to the actual active set of validators, the amount of bonded KSI on validators on the waiting list as well as the maximum number of validators, which can be increased or decreased by our voting mechanism as well.
 
One way to estimate the minimum amount of KSI your validator needs to make it to the active set is to navigate to the [Targets Tab](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fws.kusari.network#/staking/targets), sort by maximum stake and look for the least amount that is needed to be eligible for the next era.. You’ll need at least this much + 1 to enter the set.


**Why does KUSARI only have 300 validators?​**

KUSARI opted to start with an active set of 300 validators to create a reasonable and solid foundation for the chain. It's important to note that different projects have different definitions of their validators/nodes, whereas for KUSARI, every validator is running their own validating node that performs full verification of the Chain, votes on finality and produces blocks in their decided slots. Comparable projects operate on about 150 active validators.

Additionally, the validation is not the sole source of staking. Nominators participate in the staking system as well and receive rewards on the funds they are willing to commit/bond.
For every validator, there is a maximum of 256 Nominations possible, totalling in up  to 76,800 participants for the reward system.
The amount of active validators can be changed later by decision of the community through fair and decentralised governance decisions.

Further Information can be found here: [Validation](https://docs.kusari.network/validator-guides/validator/) and [Nomination](https://docs.kusari.network/what-to-try/nominator/)
 
 
**What is the block time of KUSARI?​**

Kusari is currently operating at a blocktime of approximately six seconds.
This may be changed in the future. It may be lowered to two or three seconds after optimizations, or potentially increase due to unforeseen circumstances.
 

**Does KUSARI have smart contracts?​**

Yes and No. Inherently, the KUSARI Chain does not implement smart contracts. The possibility to deploy smart contracts stems from the implementation of the EVM-Pallet, enabling any smart contract (that was written using solidity) to be deployed onto the KUSARI ecosystem.

 
**What is the inflation rate of KSI?​**

The inflation rate is based on the amount of KSI tokens locked in staking. Assuming the ideal staking rate of 50%is reached, the inflation is set to approximately 10% per year. A higher percentage staked will result in a sharp drop of the interest as well as the inflation rate to incentivize the unbonding of funds and to avoid running into shortage of liquidity.

**Comment by Neidhardt87** [comment]
### **Networking​**


**What is libp2p?​**

[Libp2p](https://libp2p.io/) is a modular and extensible networking stack that is used by IPFS, Substrate, and many other projects. It is a collection of peer-to-peer protocols for finding peers and connecting to them. Its modules have logic for content routing, peer routing, peer discovery, different transports, and NAT traversals. It is intended to be used by applications for building large scale peer-to-peer networks by only selecting the parts of the protocol suite that are needed.
The Rust implementation of the specification was built and primarily maintained by a team of contributors at Parity Technologies. The Go and JavaScript versions are maintained by Protocol Labs as well as community contributors. A [Nim](https://github.com/status-im/nim-libp2p) version of the library also exists. Libp2p as a whole is an open source project that is actively developed and expanded on various code repositories hosted on their [GitHub](https://github.com/libp2p).


**Does KUSARI use libp2p?​**

Yes, since KUSARI is built with Substrate. Substrate uses a networking protocol that is based on libp2p (specifically the Rust libp2p library). However, Substrate uses a mix of standard libp2p protocols and protocols that are homegrown and not official libp2p standards. Of the standard protocols, those which are shared with other implementations of libp2p such as IPFS, are connection-checking (ping), asking for information on a peer (identity), and Kademlia random walks (kad).
Of the protocols that are custom to Substrate, there are the legacy Substrate stream, a request-response for getting information on blocks (sync), a light client protocol, a notification protocol for transactions, and block announcement. For detailed information on how Substrate uses libp2p and the standard and custom protocols, please see the [networking documentation](https://docs.substrate.io/rustdocs/latest/sc_network/index.html).


**How does libp2p differ from IPFS?​**

The [Interplanetary File System](https://ipfs.io/) (IPFS) is a peer-to-peer hypermedia protocol used primarily for storage of files. It allows one to upload a file onto the network and share it with its content addressable URI. IPFS, like Substrate, is an application of libp2p and exists higher on the technology stack. Although both IPFS and Substrate use libp2p, it cannot be said that Substrate "uses" IPFS since besides sharing the underlying library for networking there is no native integration between the two applications.


**### KUSARI**


**What is the minimum amount of KSI I can have in my account?​**
0.1 KSI ? <- Check if thats correct


**What are the transfer fees for KUSARI?​**

It is important to note that the cost of transferring KSM is dynamic. Currently, the minimum cost of transferring KSI is ~1.5 milliKSI, although this can be changed via governance. However, actual transaction fees will vary based on a variety of factors. Specifically, fee calculation follows the following formula:

base_fee + (tx_length * length_fee) + WeightToFee(weight)

For further information please visit the Substrate documentation on [fee calculation](https://docs.substrate.io/v3/runtime/weights-and-fees/).

**NOTE**: On the EVM side the fee is set to 50GWEI, which can be either decreased or increased.

**Comment by Neidhardt87** [comment]
### **Governance​**

 
**What keeps KUSARIs governance from failing?​**

KUSARIs governance has already been shown to work. Examples can be found in the runtime upgrades that have successfully taken place through on the testnets as well as in a real economic environment on Kusama and Polkadot itself.
Blockchains and especially projects that focus on decentralised finance need a method to adapt and evolve while taking the interests of their community into consideration. Therefore, an on-chain governance system is of utmost importance  for the long-term success of KUSARI. Ultimately, it is the coin holders that are responsible for preventing KUSARI's governance from failing by using their economic value and convictions to guide the progression of the protocol and push the project towards true decentralised finance.


**What prevents KUSARIs governance from becoming centralised?**

A savvy reader might have noticed that the answer to the previous question endowed the coin holders with the ultimate responsibility to ensure that KUSARI’s governance does not fail. By following the train of this assertion, one might assume that KUSARIs governance is susceptible to becoming ruled by a few large token holders (called whales in trading parlance) and therefore become a mere plutocracy (rule of the rich).
There are several other mechanisms that are built-in to the governance system to resist this plutocratic tendency. One of these mechanisms is called conviction voting, and imposes greater voting power to token holders who are willing to lock their tokens on the protocol for longer lengths of time. Longer lock-ups display conviction in a vote. Conviction voting could allow a highly determined minority to overrule the vote of an apathetic majority in certain situations. Another mechanism is known as Adaptive Quorum Biasing. This makes proposals have a varying threshold for approval or rejection based on what part of the governance protocol the proposal originated in. For details on the subtleties of KUSARI’s governance system, please check out our [Governance documentation](https://docs.kusari.network/what-to-try/democracy/#voting-on-referendum).
<- 99% copy from dot

**Comment by Petar-23** [comment]
pls delete
